### ISSUE TITLE
Support multi-lingual concepts

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-document#18]
Sample 1
<img width="643" alt="Screenshot 2021-11-18 at 2 12 48 PM" src="https://user-images.githubusercontent.com/11865/142362093-b6ddbf9a-61a2-4edc-bc4d-e7f9e373601b.png">

Sample 2
<img width="618" alt="Screenshot 2021-11-18 at 2 12 58 PM" src="https://user-images.githubusercontent.com/11865/142362114-5b03cb4c-53c5-4813-8c8f-3809fc7de3b7.png">

**Comment by opoudjis** [comment]
We will have designations in multiple languages, with existing markup using metadata attributes of designations.

The English and French terms are not just designations, but two different languages' versions of the same term. We are going to introduce language as a tag of terms, just as it already a tag of clauses; and we will use multilingual formatting (the `@name` attribute) to align the English and French term in Semantic XML. We will fold the French under the English term in Presentation XML; and we will need to update the xrefs to account for the fact that there are less terms as a result than there used to be.

**Comment by opoudjis** [comment]
The French-language term has French metalanguage: term note label, term example label, related term label, term source label. These all need to be redone in French.

**Comment by opoudjis** [comment]
1. "modified" needs to be bilingual (French and English)—I will need to move the resolution of <modified> to Presentation XML

2. Arabic, I have finally hit RTL, <> is not wrapping correctly

3. There is random ordering of termnotes and termexamples between English and French, I need to order them in Presentation XML, not HTML

**Comment by opoudjis** [comment]
Move rearranging of term notes before term examples to Presentation XML, so that merger of English and French term can happen after it.

**Comment by opoudjis** [comment]
Do not term a term designation from expression to letter-symbol if it has textual content: `stem:[gamma]-ray` is an expression, not a letter-symbol.

**Comment by opoudjis** [comment]
Two other-language terms in the same language are displayed in the same definition list entry, separated by line break.
