### ISSUE TITLE
Remaining issues: term referencing, NOTE conversion failure

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-document#19]
<img width="662" alt="Screenshot 2021-11-19 at 12 03 40 PM" src="https://user-images.githubusercontent.com/11865/142562961-b8338724-0a71-4eed-b706-4c96a2f6546a.png">
<img width="701" alt="Screenshot 2021-11-19 at 12 04 57 PM" src="https://user-images.githubusercontent.com/11865/142563064-8933055b-f7bc-42c9-90ac-fe15b5d65534.png">

**Comment by ronaldtse** [comment]
Term reference issue still present, now

PDF: 
<img width="712" alt="Screenshot 2021-11-28 at 9 38 48 PM" src="https://user-images.githubusercontent.com/11865/143770244-b9216012-0057-455c-991c-91f627632aa0.png">

<img width="714" alt="Screenshot 2021-11-28 at 9 39 08 PM" src="https://user-images.githubusercontent.com/11865/143770258-07580086-1d1d-4004-babc-06afa59130e4.png">

and

HTML:
<img width="858" alt="Screenshot 2021-11-28 at 9 39 27 PM" src="https://user-images.githubusercontent.com/11865/143770269-10c4ffaf-9d01-4ebf-a098-598d40fc13c4.png">
<img width="856" alt="Screenshot 2021-11-28 at 9 39 32 PM" src="https://user-images.githubusercontent.com/11865/143770274-0ae7aa1a-0c25-42b7-b8f7-7c746c4cbbc4.png">

**Comment by opoudjis** [comment]
Rendering `{{...}}` as something in parentheses is correct behaviour, so I'm going to strip the parentheses in the YAML postprocessing. (In fact, that was a typo in the script, I meant to do that.)

**Comment by ronaldtse** [comment]
There are duplicated parentheses in the immediate last screenshots, which is a rendering issue.

**Comment by opoudjis** [comment]
No, Ronald, that is a source code issue. The source is `({{IEV}})`, and it should be `{{IEV}}`.

**Comment by ronaldtse** [comment]
192-10-16:
```adoc
==== error recovery

automatic detection, control and correction of an internal erroneous state

NOTE: The purpose of error recovery is to avoid a failure of the whole system, following a failure of one of its subsystems or components.

Note 2: See also backward error recovery ({{<<IEV:192-10-17>>,192-10-17}}) and forward error recovery ({{<<IEV:192-10-18>>,192-10-18}}).

Note 3: Error recovery often makes use of redundancy and diversity.
```

True. Thanks.
