### ISSUE TITLE
Modified and Termsource processing change

### ISSUE THREAD

**Issue by opoudjis** [glossarist/iev-document#23]
Resulting from https://github.com/glossarist/iev-document/issues/18

I am eliminating the `<modification>` tag from Presentation XML, inserting the relevant text directly into Presentation XML. So:

````
      <termsource status='identical'>
          <origin citeas=''>
            <termref base='IEV' target='xyz'>t1</termref>
          </origin>
        </termsource>
        <termsource status='modified'>
          <origin citeas=''>
            <termref base='IEV' target='xyz'/>
          </origin>
          <modification>
            <p id='_'>with adjustments</p>
          </modification>
        </termsource>
````

is replaced by

````
       <termsource status="identical">[SOURCE: <origin citeas="">
             <termref base="IEV" target="xyz">t1</termref>
           </origin>]</termsource>;
         <termsource status="modified">[SOURCE: <origin citeas="">
             <termref base="IEV" target="xyz"/>
           </origin>, modified
            &#x2013;
             with adjustments]</termsource>
````

I don't believe you will need to change anything to deal with this.

**Comment by Intelligent2013** [comment]
To do: change in xslt:
- [x] don't display localize string `source`
- [x] don't display brackets `[` `]`
- [x] first text between `termsource` and `origin`, and after `[` (if exist) render in bold for 'ogc' and 'rsd', and in color for 'rsd'.

**Comment by opoudjis** [comment]
@Intelligent2013 : I will do last point, boldface; the colour is news to me.

**Comment by Intelligent2013** [comment]
@opoudjis 
- OGC example - `SOURCE:` boldfaced:
![image](https://user-images.githubusercontent.com/5559926/145721620-280d7cfb-b682-4cac-baa8-eb561b438138.png)

- RSD example (note: there isn't brackets around) - `SOURCE:` boldfaced and in color:
![image](https://user-images.githubusercontent.com/5559926/145721575-e5193784-6aa9-4978-932e-d64f6c5c0fad.png)

- Also there is a feature in PAS documents - if source is non-standard thing, then curly braces are using around:
![image](https://user-images.githubusercontent.com/5559926/145721945-6190450d-226f-4ea5-b1d3-bf03d17ec4f7.png)
(from https://github.com/metanorma/mn-samples-bsi/tree/main/reference-docs/pas/pas-7340)

**Comment by opoudjis** [comment]
Done OGC and RSD: no colour added to RSD, just `<strong>`

**Comment by Intelligent2013** [comment]
XSLTs updated.
