### ISSUE TITLE
Fix IEV document errors

### ISSUE THREAD

**Issue by opoudjis** [glossarist/iev-document#4]

**Comment by ronaldtse** [comment]
```
AsciiDoc Input: (Section: verification): term reference not in expected format:ISO 9000:2005, 3.8.4, Note 2 has been modified and Note 3 has been added
AsciiDoc Input: (Section: validation): term reference not in expected format:ISO 9000:2005, 3.8.5, Notes 3, 4 and 5 have been added
AsciiDoc Input: (Section: test): term reference not in expected format:ISO 9000:2005, 3.8.3, to place the emphasis on “procedure”
AsciiDoc Input: (Section: backward recovery): term reference not in expected format:ISO/IEC/IEEE 24765:2010, 3.234 (2), by omission of "type of" or other relevant words and addition of Notes 1 and 2
AsciiDoc Input: (Section: forward recovery): term reference not in expected format:ISO/IEC/IEEE 24765:2010, 3.1185 (2), by omission of "type of" or other relevant words and addition of Note 1
AsciiDoc Input: (Section: fault masking): term reference not in expected format:ISO/IEC/IEEE 24765:2010, 3.1125, by addition of Note 1
Crossreferences: (XML Line 000322): IEV does not have a corresponding anchor ID in the bibliography!
Style: (XML Line 000287): Document must contain at least one clause
Style: (XML Line 000287): Document must contain clause after Terms and Definitions
Style: Document must include (references) Normative References
Style: Final section must be (references) Bibliography
```

**Comment by opoudjis** [comment]
Errors I'm now getting:

````
AsciiDoc Input: (Section: process): term reference not in expected format:ISO 9000:2005, 3.4.1
AsciiDoc Input: (Section: requirement): term reference not in expected format:ISO 9000:2005, 3.1.2
AsciiDoc Input: (Section: conformity): term reference not in expected format:ISO 9000:2005, 3.6.1
AsciiDoc Input: (Section: non conformity): term reference not in expected format:ISO 9000:2005, 3.6.2
AsciiDoc Input: (Section: verification): term reference not in expected format:ISO 9000:2005, 3.8.4, modified – Note 2 has been modified and Note 3 has been added
AsciiDoc Input: (Section: validation): term reference not in expected format:ISO 9000:2005, 3.8.5, modified – Notes 3, 4 and 5 have been added
AsciiDoc Input: (Section: system software): term reference not in expected format:ISO/IEC 2382-1:1993, 01.04.02
AsciiDoc Input: (Section: line of maintenance): term reference not in expected format:EN 13306
AsciiDoc Input: (Section: test): term reference not in expected format:ISO 9000:2005, 3.8.3, modified to place the emphasis on “procedure”
AsciiDoc Input: (Section: backward recovery): term reference not in expected format:ISO/IEC/IEEE 24765:2010, &lt;i&gt;Systems and software engineering – Vocabulary&lt;/i&gt;, 3.234 (2), modified by omission of "type of" or other relevant words and addition of Notes 1 and 2
AsciiDoc Input: (Section: forward recovery): term reference not in expected format:ISO/IEC/IEEE 24765:2010, &lt;i&gt;Systems and software engineering – Vocabulary&lt;/i&gt;, 3.1185 (2), modified by omission of "type of" or other relevant words and addition of Note 1
AsciiDoc Input: (Section: fault masking): term reference not in expected format:ISO/IEC/IEEE 24765:2010, &lt;i&gt;Systems and software engineering – Vocabulary&lt;/i&gt;, 3.1125, modified by addition of Note 1

Style: (XML Line 000287): Document must contain at least one clause
Style: (XML Line 000287): Document must contain clause after Terms and Definitions
Style: Document must include (references) Normative References
Style: Final section must be (references) Bibliography
Style: (XML Line 000242): Scope may contain requirement: In producing this document, several sections of IEC 60050-191:1990 (formerly
Chapter 191) concerning quality of service, have been omitted:


sections 19 and 20: Quality of service in telecommunications, has been adopted
and developed by the International Telecommunication Union, as publication ITU-T
E.800, Definitions of terms related to quality of service; and


sections 21 to 30, inclusive: Quality of service in electric power systems is
to be developed as a new document, IEC 60050-6921
Style: (XML Line 000242): Scope may contain permission: The document is not an exhaustive vocabulary for all IEC standards in the
dependability field: definitions for some specialized terms may only be found in
the relevant standards
Style: (XML Line 000001): Definition may contain requirement: 
  time interval for which the item is required to be in an up state
Style: (XML Line 000001): Definition may contain requirement: 
  position in an organization where specified levels of maintenance are to be carried out
Style: (XML Line 000087): Table should have title
Bibliography: (XML Line 000308): Term "system" does not match IEV 151-11-27, modified by extension to suit the dependability context ""
Bibliography: (XML Line 001984): Term "true value" does not match IEV 311-01-04 "true value (of a quantity)"
Bibliography: (XML Line 002002): Term "expectation" does not match IEV 103-08-10 "expectation, <of a random variable>mean, <of a random variable>"
Bibliography: (XML Line 002033): Term "-fractile" does not match IEV 103-08-14 "p-fractile, <of a probability distribution>p-quantile, <of a probability distribution>"
Style: (XML Line 000441): degradation: term definition ends with period
Style: (XML Line 001058): instantaneous failure rate: term definition ends with period
Style: (XML Line 001083): instantaneous failure intensity: term definition ends with period
Style: (XML Line 001809): error recovery: term definition ends with period
````

**Comment by opoudjis** [comment]
scripts/split_codes.rb is dumping unparsed text as sources, instead of actual references; it is only parsing IEV references correctly.

**Comment by opoudjis** [comment]
https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=192-06-03 cites `EN 13306`. I have no idea what that is supposed to be. And more critically, neither does Relaton.

**Comment by opoudjis** [comment]
Checks "Document must contain at least one clause" and "Document must contain clause after Terms and Definitions" do not apply to IEV documents. Will address by injecting bibdata/ext/subdoctype = "vocabulary" for any document with identifier IEC 60050

**Comment by opoudjis** [comment]
````
Bibliography: (XML Line 000308): Term "system" does not match IEV 151-11-27, modified by extension to suit the dependability context ""
Bibliography: (XML Line 001984): Term "true value" does not match IEV 311-01-04 "true value (of a quantity)"
Bibliography: (XML Line 002002): Term "expectation" does not match IEV 103-08-10 "expectation, <of a random variable>mean, <of a random variable>"
Bibliography: (XML Line 002033): Term "-fractile" does not match IEV 103-08-14 "p-fractile, <of a probability distribution>p-quantile, <of a probability distribution>"
Style: (XML Line 000441): degradation: term definition ends with period
Style: (XML Line 001058): instantaneous failure rate: term definition ends with period
Style: (XML Line 001083): instantaneous failure intensity: term definition ends with period
Style: (XML Line 001809): error recovery: term definition ends with period
````

These are all errors (yes, errors) in the source YAML files.

**Comment by opoudjis** [comment]
Need to adjust relative positioning of subdoctype and horizontal in IEC and ISO.

**Comment by opoudjis** [comment]
The source files, grotesquely, include the title along with the reference as the clause designation:

`<i>Systems and software engineering – Vocabulary</i>, 3.234 (2), modified by omission of \"type of\" or other relevant words and addition of Notes 1 and 2`

No. Randomly inserting citation titles into citations is unacceptable, and I will be stripping the title from those citations.

**Comment by opoudjis** [comment]
usageinfo has been erroneously processed in script extraction as a random piece of text outside of designations:

`alt:[available state] <of an item;>`

`<admitted><expression><name>available state</name></expression></admitted> &lt;of an item;&gt;`

Neither the extraction script, nor the yaml going into it, are of acceptable quality; and fixing the former is not addressing all the issues in the latter.

**Comment by opoudjis** [comment]
Enragingly, usageinfo is being tagged to individual designations, and not to the entire term.

Usageinfo was explicitly modelled as an attribute of a term, NOT a designation. There has been no provision made for usage info specific to designations. I will require 

* confirmation that usage info can apply to designations and not just terms
* confirmation that `<...>` is correct rendering of usage info

**Comment by ronaldtse** [comment]
> ````
> 
> Bibliography: (XML Line 000308): Term "system" does not match IEV 151-11-27, modified by extension to suit the dependability context ""
> 
> Bibliography: (XML Line 001984): Term "true value" does not match IEV 311-01-04 "true value (of a quantity)"
> 
> Bibliography: (XML Line 002002): Term "expectation" does not match IEV 103-08-10 "expectation, <of a random variable>mean, <of a random variable>"
> 
> Bibliography: (XML Line 002033): Term "-fractile" does not match IEV 103-08-14 "p-fractile, <of a probability distribution>p-quantile, <of a probability distribution>"
> 
> Style: (XML Line 000441): degradation: term definition ends with period
> 
> Style: (XML Line 001058): instantaneous failure rate: term definition ends with period
> 
> Style: (XML Line 001083): instantaneous failure intensity: term definition ends with period
> 
> Style: (XML Line 001809): error recovery: term definition ends with period
> 
> ````
> 
> 
> 
> These are all errors (yes, errors) in the source YAML files.

Some of these are IEV "search" mismatches due to the mode mismatch. In Glossarist math is really in MathML, not sure if Metanorma's IEV search is handling it.

**Comment by ronaldtse** [comment]
> Need to adjust relative positioning of subdoctype and horizontal in IEC and ISO.

We may want to have IEV as a document subtype? Sounds about right...

**Comment by ronaldtse** [comment]
`EN 13306` is a European Standard / CEN standard. We do have relaton-cen, but perhaps it's not integrated with Metanorma.

**Comment by opoudjis** [comment]
Stem expression randomly occurring in its own paragraph in the middle of definition, 192-05-06, is being extracted and processed as an alternate, admitted expression, instead of as a nonverbal expression.

We have three different cases for formulas:

* Formula before definition prose in a term is an admitted term
* Formula halfway through a definition in a term is still part of a definition; e.g. 192-05-06
* Formula at the end of a definition is part of a definition by default

To make it clear what is going on: a non-verbal definition needs to be given as its own definition entry. So:

````
    average value of the instantaneous failure rate over a given time interval (stem:[t]~1~, stem:[t]~2~)

    stem:[bar lambda ( t_1 , t_2 ) = (1)/((t_2 - t_1)) int_( t_1)^( t_2) lambda ( t ) d t]
````

is just a single definition, whereas

````
    [.definition]
    average value of the instantaneous failure rate over a given time interval (stem:[t]~1~, stem:[t]~2~)

    [.definition]
    stem:[bar lambda ( t_1 , t_2 ) = (1)/((t_2 - t_1)) int_( t_1)^( t_2) lambda ( t ) d t]
````

shall make the formula a separate definition, and treat it as a non-verbal definition.

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton-cen/issues/2

**Comment by opoudjis** [comment]
Remaining errors:

````
Bibliography: (XML Line 002291): Term "true value" does not match IEV 311-01-04 "true value (of a quantity)"
Bibliography: (XML Line 002314): Term "expectation" does not match IEV 103-08-10 "expectation, <of a random variable>mean, <of a random variable>"
Bibliography: (XML Line 002355): Term "p-fractile" does not match IEV 103-08-14 "p-fractile, <of a probability distribution>p-quantile, <of a probability distribution>"
````

> Some of these are IEV "search" mismatches due to the mode mismatch. In Glossarist math is really in MathML, not sure if Metanorma's IEV search is handling it.

**Comment by opoudjis** [comment]
IEV, with lamentable inconsistency, are including field-of-application information, in brackets or angle brackets, in the retrieved text from Electropedia.

So 311-01-04

* preferred: true value
* field of application: of a quantity
* retrieved text from IEV: "true value (of a quantity)"

103-08-10:

* preferred: expectation
* field of application: of a random variable
* retrieved text from IEV: 

````
*expectation*, <of a random variable>
*mean*, <of a random variable>
````

103-08-14:

* preferred: p-fractile
* retrieved text from IEV: 
* retrieved text from IEV:


````
*_p_-fractile*, <of a probability distribution>
*_p_*-quantile, <of a probability distribution>
````

IEV is now retrieving the pure text of the IEV term, `doc.at(xpath)&.text&.strip`. It has to parse the HTML to remove bracketed text, and second lines.

**Comment by opoudjis** [comment]
I won't fix "true value (of a quantity)": I don't have confidence that () can be reliably treated in IEV as a field of application.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , can you file the source data error in the iev-data repo so we can clarify with IEC? Ultimately it may fall to us to fully clean up the IEV content.
